---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: azure-key-vault-controller
    chart: azure-key-vault-controller-1.1.6
    heritage: Helm
    release: akv2k8s-kvcontroller
  name: akv2k8s-kvcontroller-azure-key-vault-controller
  namespace: admin

---
apiVersion: v1
data: null
kind: Secret
metadata:
  labels:
    app: azure-key-vault-controller
    chart: azure-key-vault-controller-1.1.6
    heritage: Helm
    release: akv2k8s-kvcontroller
  name: akv2k8s-kvcontroller-azure-key-vault-controller-env
  namespace: admin

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: azure-key-vault-controller
    chart: azure-key-vault-controller-1.1.6
    heritage: Helm
    release: akv2k8s-kvcontroller
  name: akv2k8s-kvcontroller-azure-key-vault-controller
  namespace: admin
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: azure-key-vault-controller
    chart: azure-key-vault-controller-1.1.6
    heritage: Helm
    release: akv2k8s-kvcontroller
  name: akv2k8s-kvcontroller-azure-key-vault-controller-reader
  namespace: admin
rules:
- apiGroups:
  - spv.no
  resources:
  - azurekeyvaultsecrets
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: azure-key-vault-controller
    chart: azure-key-vault-controller-1.1.6
    heritage: Helm
    release: akv2k8s-kvcontroller
  name: akv2k8s-kvcontroller-azure-key-vault-controller
  namespace: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: akv2k8s-kvcontroller-azure-key-vault-controller
subjects:
- kind: ServiceAccount
  name: akv2k8s-kvcontroller-azure-key-vault-controller
  namespace: admin

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: azure-key-vault-controller
    chart: azure-key-vault-controller-1.1.6
    heritage: Helm
    release: akv2k8s-kvcontroller
  name: akv2k8s-kvcontroller-azure-key-vault-controller-reader
  namespace: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: akv2k8s-kvcontroller-azure-key-vault-controller-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: azure-key-vault-controller
    chart: azure-key-vault-controller-1.1.6
    heritage: Helm
    release: akv2k8s-kvcontroller
  name: akv2k8s-kvcontroller-azure-key-vault-controller
  namespace: admin
spec:
  selector:
    matchLabels:
      app: azure-key-vault-controller
      release: akv2k8s-kvcontroller
  template:
    metadata:
      labels:
        app: azure-key-vault-controller
        release: akv2k8s-kvcontroller
    spec:
      containers:
      - args:
        - --cloudconfig=/etc/kubernetes/azure.json
        env:
        - name: AZURE_VAULT_NORMAL_POLL_INTERVALS
          value: 1m
        - name: AZURE_VAULT_EXCEPTION_POLL_INTERVALS
          value: 10m
        - name: AZURE_VAULT_MAX_FAILURE_ATTEMPTS
          value: "5"
        - name: CUSTOM_AUTH
          value: "false"
        - name: LOG_LEVEL
          value: info
        - name: LOG_FORMAT
          value: fmt
        image: spvest/azure-keyvault-controller:1.1.0
        imagePullPolicy: IfNotPresent
        name: azure-keyvault-controller
        volumeMounts:
        - mountPath: /etc/kubernetes/azure.json
          name: azure-config
          readOnly: true
      serviceAccountName: akv2k8s-kvcontroller-azure-key-vault-controller
      volumes:
      - hostPath:
          path: /etc/kubernetes/azure.json
          type: File
        name: azure-config

